### ISSUE TITLE
這個打算怎麼部署？

### ISSUE THREAD

**Issue by sparanoid** [leancloud/open-old#1]
這個打算怎麼部署？如果是放到 GitHub Pages 上，這個 repo 要改名為 `avoscloud.github.io`，如果要部署到我們的服務器或 AVOS Cloud 上就沒這個問題了

**Comment by hjiang** [comment]
部署到我们的服务器吧。github pages 就当是 preview 好了。

**Comment by sparanoid** [comment]
不放在 GitHub Pages 上的話 branch 不必是 `gh-pages` 了

**Comment by hjiang** [comment]
嗯，但是在 github 也部署一份可以做预览。 http://avoscloud.github.io/open/—
