### ISSUE TITLE
「代码分支管理指南」需要补充多人协作开发一个功能的部分

### ISSUE THREAD

**Issue by wangxiao** [leancloud/open-old#11]
实践中按照我们的「代码分支管理指南」，合作开发一个功能这种情况还是比较难解决。

各写各的没问题，如果有合作一个功能开发，需要再开一个新分支来协同写程序，写完了一起 pull request 到 master 上。所以一个 repo 就不一定是两个分支，需要修改下这个指南。

如果要保持两个分支，需要 fork 某个人的 repo 开发同一功能，这样做的成本比在主库上面新开一个分支大些，所以这种情况开多个分支更好。

cc @sunchanglong @sparanoid

**Comment by hjiang** [comment]
我还是希望主 repo 不要有 feature branch，不然很难规范管理。要和另一个人协作开发他的 repo 的一个分支，只需要在自己本地增加一个 git remote 就可以，不用在 GitHub 上增加任何新的 branch，也不用 fork 他的 repo。

**Comment by wangxiao** [comment]
好的。
